### ISSUE TITLE
Update flutter_map dependency

### ISSUE THREAD

**Issue by jithware** [jithware/mappoff#6]
Update [flutter_map](https://pub.dev/packages/flutter_map) dependency to latest version

Depends on https://github.com/lpongetti/flutter_map_marker_cluster/pull/120 being completed

**Comment by jithware** [comment]
In release >= 1.0.0+25

Using method https://github.com/lpongetti/flutter_map_marker_cluster/pull/120#issuecomment-1162922318 to avoid https://github.com/lpongetti/flutter_map_marker_cluster/pull/120 pull dependency. Will use direct reference when pull complete.

**Comment by pablojimpas** [comment]
Version `0.5.0` is now available on pub.dev with the PR merged, so you can stop relaying on my branch.
